In [1]:
import numpy as np

In [2]:
arr=np.array([[34,56,378],[65,98,300],[28,66,11]])

In [3]:
arr

array([[ 34,  56, 378],
       [ 65,  98, 300],
       [ 28,  66,  11]])

In [4]:
transpose_arr=np.transpose(arr)

In [5]:
transpose_arr

array([[ 34,  65,  28],
       [ 56,  98,  66],
       [378, 300,  11]])

In [6]:
trans_arr=arr.T

In [7]:
trans_arr

array([[ 34,  65,  28],
       [ 56,  98,  66],
       [378, 300,  11]])